print("Hi my name is RudeAI. ")
print("I would like to ask you a few questions." )
name = input("What is your name? ")
print(name,"? I hate your name! It sounds so stupid; you should really consider changing it. ")
age = int(input("How old are you, " +name+ "? "))
print("Oh, you are" ,age,". Man you are an old fart!")
fun = input("What do you like to do for fun, " + name + "?")
print(fun,"?! Who actually likes to do that?")
singer = input("Who is your favorite singer? ")
print("Nobody likes" , singer,". Gosh, you have bad taste." )
siblings = input("How many siblings do you have?" )
print("Only" ,siblings, "?? You should really have more; I have 20!")
idol = input("Who do idolize or look up to?" )
print("You have got to be kidding me. How could you idolize " , idol , )
print("when you could have me as your idol?!")
print("So" , name , "you are" , age , "years old...")
print("You like to" , fun , "for fun and you like the singer," , singer ,".")
print("You look up to",idol,", for some stupid reason.")
print("I am just messing with you" , name ,".")
